/*
 * HelloApiSchema
 *
 * Practice api schema
 *
 * API version: 1.0.0
 * Contact: doriven@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// UserApiService is a service that implements the logic for the UserApiServicer
// This service should implement the business logic for every endpoint for the UserApi API.
// Include any external packages or services that will be required by this service.
type UserApiService struct {
}

// NewUserApiService creates a default api service
func NewUserApiService() UserApiServicer {
	return &UserApiService{}
}

// CreateUser - 
func (s *UserApiService) CreateUser(ctx context.Context, createUserInput CreateUserInput) (ImplResponse, error) {
	// TODO - update CreateUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, CreateUserOutput{}) or use other options such as http.Ok ...
	//return Response(200, CreateUserOutput{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateUser method not implemented")
}

// GetUser - 
func (s *UserApiService) GetUser(ctx context.Context, id int64) (ImplResponse, error) {
	// TODO - update GetUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetUserOutput{}) or use other options such as http.Ok ...
	//return Response(200, GetUserOutput{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUser method not implemented")
}

// GetUserList - 
func (s *UserApiService) GetUserList(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetUserList with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetUserListOutput{}) or use other options such as http.Ok ...
	//return Response(200, GetUserListOutput{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUserList method not implemented")
}
