openapi: 3.0.1
info:
  title: Greeting Server
  version: 1.0.0
servers:
- url: /
paths:
  /hello:
    get:
      operationId: getGreeting
      parameters:
      - description: defaults to World if not given
        in: query
        name: name
        schema:
          type: string
      responses:
        "200":
          content:
            text/plain:
              schema:
                description: contains the actual greeting as plain text
                type: string
          description: returns a greeting
components:
  schemas: {}
x-original-swagger-version: "2.0"
