name: deploy-go

on:
  push:
      branches:
        - main
      paths:
        - 'server/*'

env:
  ECR_REGISTRY: 749794220379.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_REPOSITORY: first-ecr-jackyutajack
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}     

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: server
          file: serveer/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      
