name: CI
on:
  push:
      branches:
        - main
      paths:
        - 'client/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build

      - name: Deploy
        working-directory: client/dist
        run: |
          aws s3 sync . s3://first-s3-jackyutajack --delete 
